numpy-----------


In [25]:
import numpy as np
import numpy.char as char

In [8]:
li1=[1,3,5,2]
arr1=np.array(li1)#one-dimension
li2=[2,4,6,8],[3,6,9,12]#two-dimension
arr2=np.array(li2)

In [10]:
#.shape-----tells the no. of rows and columns
arr1.shape
arr2.shape

(2, 4)

In [12]:
arr2

array([[ 2,  4,  6,  8],
       [ 3,  6,  9, 12]])

In [13]:
arr2[ : , [0, -1] ]

array([[ 2,  8],
       [ 3, 12]])

In [21]:
###EDA
arr1[arr1>2]
arr2.reshape(4,2)

array([[ 2,  4],
       [ 6,  8],
       [ 3,  6],
       [ 9, 12]])

In [36]:
#mechanism to create an array
np.arange(1,20,2).reshape(2,5)

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19]])

In [47]:
#operations
arr1*arr1
np.ones(3)
np.zeros(4)
np.random.randint(10)#rNDOM NUMBERS
np.random.randint(10,50,2)#2-----how many nos...




array([23, 40], dtype=int32)

In [48]:
#based on normalisation
np.random.randn(2,4)

array([[-0.32362545, -0.0040276 , -0.25414433, -0.33003584],
       [ 0.83633863,  0.32254318, -1.05944461, -1.61866953]])

In [50]:
np.random.random_sample((4,3))

array([[0.45131034, 0.99301794, 0.60450692],
       [0.13662065, 0.23306868, 0.16616021],
       [0.17490637, 0.78713757, 0.01557136],
       [0.45832458, 0.64348397, 0.91908077]])